//created on: 12.01.2017
package de.hdm.wim

//list any import classes here.



//declare any global variables here
declare Event
	@role(event)
end
declare ComplexTokenEvent
	@role(event)
end

declare window LastEvents
	// Aktuelle wird mitgezaehlt
	Event() over window:length(2)
end

declare window LongLastEvents
	// Aktuelle wird mitgezaehlt
	Event() over window:length(20)
end

declare window LastComplexTokenEvent
	ComplexToken() over window:length(1)
end


rule "Check last tokens if Date"
	no-loop
    when
        ($day : Event(
			token == "thursday"
		) from window LastEvents
		and
		$appointment : Event(
			token == "appointement"
			|| token == "meeting"
		) from window LongLastEvents)
		$complexTokenEvent : ComplexTokenEvent() from window LastComplexTokenEvent
    then
        modify($complexTokenEvent) {
			setRestrictedToTime($day.getToken())
		}
		System.out.println("Set meeting for " + $day.getToken() + ".");
end
/*
rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
*/