package de.hdm.wim.expert

//list any import classes here.
import de.hdm.wim.expert.MessageListener


//declare any global variables here


rule "Identify projectdocuments"
    when
        // Token = "Current activities", "Documents"
        ml : MessageListener(
        		prevToken != currentToken
        		&& (
        			currentToken == "current activities"
        			|| currentToken == "documents"
        		)
        		, prevToken : currentToken
        	)
    then
        ml.setRequestedObject(MessageListener.PROJECTDOCUMENTS);

end

rule "Recognize restriction"
    when
        //conditions
        ml : MessageListener(
        	prevToken != currentToken
        	&& (
        		currentToken == "concerning"
        		|| currentToken == "leading to"
        	)
        	, prevToken : currentToken
        	)
    then
        //actions
        ml.setNextIsRestriction(true);

end

rule "Add restriction"
    when
        //conditions
        ml : MessageListener(
        		prevToken != currentToken
        		&& ml.nextIsRestriction
        		&& requestedObject == MessageListener.PROJECTDOCUMENTS
        		, restriction : currentToken
        	)
    then
        //actions
        ml.setRestriction(restriction);

end