package de.hdm.wim.expert

//list any import classes here.
import de.hdm.wim.expert.MessageListener


//declare any global variables here


rule "Identify projectdocuments"
    when
        // Token = "Current activities", "Documents"
        ml : MessageListener(
        		prevToken != currentToken
        		&& (
        			currentToken == "current activities"
        			|| currentToken == "documents"
        		)
        		, prevToken : currentToken
        	)
    then
        ml.setRequestedObject(MessageListener.PROJECTDOCUMENTS);

end

rule "Recognize relation"
    when
        //conditions
        ml : MessageListener(
        	prevToken != currentToken
        	&& (
        		currentToken == "concerning"
        		|| currentToken == "leading to"
        	)
        	, prevToken : currentToken
        	)
    then
        //actions
        ml.setNextIsRelated(true);

end

rule "Add relation"
    when
        //conditions
        ml : MessageListener(
        		prevToken != currentToken
        		&& ml.nextIsRelated
        		&& requestedObject == MessageListener.PROJECTDOCUMENTS
        		, relation : currentToken
        	)
    then
        //actions
        ml.setRelation(relation);

end
