package de.hdm.wim

//list any import classes here.
import de.hdm.wim.Token


//declare any global variables here
declare Token
	@role(event)
end

declare window LastEvents
	// Aktuelle wird mitgezaehlt
    Token() over window:length(4)
end

rule "Fusion - Identify projectdocuments"
    when
        $ml : Token(
        		prevToken != currentToken
        		&& (
        			currentToken == "current activities"
        			|| currentToken == "documents"
        		)
        		, prevToken : currentToken
        	)
    then
    	modify($ml) {
    		setPrevToken(prevToken),
    		setRequestedObject(Token.PROJECTDOCUMENTS)
    	}
end


rule "Fusion - Recognize restriction"
    when
        $ml : Token(
        		prevToken != currentToken
        		&& (
        			currentToken == "concerning"
        			|| currentToken == "leading to"
        		)
        		, restriction : currentToken
        	)
        $objectEvent : Token(
        	requestedObject == Token.PROJECTDOCUMENTS
        ) from window LastEvents

    then
       	System.out.println("Await restriction!");
       	modify($ml) {
       		setPrevToken(restriction),
       		setRequestedObject($objectEvent.getRequestedObject()),
       		setAwaitRestriction(true)
       	}
end

rule "Fusion - Add restriction"
    when
       	$object : Token( requestedObject == Token.PROJECTDOCUMENTS, awaitRestriction ) over window:length(2)
       	&& $restriction : Token ( requestedObject != Token.PROJECTDOCUMENTS ) over window:length(1)
    then
    	modify($object) {
    		setAwaitRestriction(false)
    	}
    	System.out.println($object.getRequestedObject() + " restricted to " + $restriction.getCurrentToken());

end

rule "Fusion - Identify due date"
    when
        $ml : Token(
        		prevToken != currentToken
        		&& (
        			currentToken == "concerning"
        			|| currentToken == "leading to"
        		)
        		, restriction : currentToken
        	)
        $objectEvent : Token(
        	requestedObject == Token.PROJECTDOCUMENTS
        ) from window LastEvents

    then
       	System.out.println("Await restriction!");
       	modify($ml) {
       		setPrevToken(restriction),
       		setRequestedObject($objectEvent.getRequestedObject()),
       		setAwaitRestriction(true)
       	}
end