//created on: 10.01.2017
package Google

//list any import classes here.
import de.hdm.wim.ComplexToken
import de.hdm.wim.Event


//declare any global variables here

declare Event
	@role(event)
end
declare ComplexToken
	@role(event)
end

declare window LastEvents
	// Aktuelle wird mitgezaehlt
    Event() over window:length(2)
end

declare window LastComplexTokenEvent
    ComplexToken() over window:length(1)
end



rule "Identify topic Google Drive"
	// Modify will cause infinite loop
	lock-on-active true
    when
        Event(
       		token == "google"
        )
        // Only most recent ComplexToken
       	$complexToken : ComplexToken() from window LastComplexTokenEvent
    then
    	modify($complexToken) {
    		addTopic(ComplexToken.DRIVE)
    	}
end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
