//created on: 09.01.2017
package de.hdm.wim

//list any import classes here.
import de.hdm.wim.LifecycleEvent
import de.hdm.wim.ComplexToken


//declare any global variables here
declare ComplexToken
	@role(event)
end

declare window LastComplexTokenEvent
    ComplexToken() over window:length(1)
end


rule "Start Lifecycle of ComplexToken"

    when
        LifecycleEvent(token == "start")
    then
    	// Reset prev ComplexToken?
        insert(new ComplexToken());

end

rule "End Lifecycle of ComplexToken"

    when
        LifecycleEvent(token == "end")
        // Only most recent ComplexToken
       	$complexToken : ComplexToken() from window LastComplexTokenEvent
    then
    	System.out.println($complexToken);

end