package de.hdm.wim

//list any import classes here.
import de.hdm.wim.ComplexToken
import de.hdm.wim.Event

//declare any global variables here
declare Event
	@role(event)
end

rule "Identify topic projectdocuments"
	// Modify will cause infinite loop
	lock-on-active true
    when
        Event(
       		token == "current activities"
        	|| token == "documents"
        )
        $complexToken : ComplexToken()
    then
    	modify($complexToken) {
    		addTopic(ComplexToken.PROJECTDOCUMENTS)
    	}
end