package de.hdm.wim

//list any import classes here.
/*import de.hdm.wim.Token

//declare any global variables here
declare Token
	@role(event)
end

rule "Identify topic projectdocuments"
    when
        $ml : Token(
        		prevToken != currentToken
        		&& (
        			currentToken == "current activities"
        			|| currentToken == "documents"
        		)
        		, prevToken : currentToken
        	)
    then
    	modify($ml) {
    		setPrevToken(prevToken),
    		setTopic(Token.PROJECTDOCUMENTS)
    	}
end
*/