//created on: 11.01.2017
package de.hdm.wim

//list any import classes here.
import de.hdm.wim.ComplexTokenEvent
import de.hdm.wim.Event


//declare any global variables here
declare Event
	@role(event)
end
declare ComplexTokenEvent
	@role(event)
end

declare window CurrentEvent
	Event() over window:length(1)
end


rule "Recognize greeting which leads to protocol(s)"
	no-loop
	when
		Event(
			token == "hi"
			|| token == "hello"
		) from window CurrentEvent
		$complexTokenEvent : ComplexTokenEvent() from window LastComplexTokenEvent
	then
		modify($complexTokenEvent) {
			addTopic(ComplexTokenEvent.PROTOCOL);
		}
end

rule "Recognize end of conversation which leads to creationrequest of protocol"
	no-loop
	when
		Event(
			token == "bye"
			|| token == "goodbye"
		) from window CurrentEvent
		$complexTokenEvent : ComplexTokenEvent() from window LastComplexTokenEvent
	then
		modify($complexTokenEvent) {
			addTopic(ComplexTokenEvent.PROTOCOLCREATION);
		}
end