//created on: 09.01.2017
package de.hdm.wim

//list any import classes here.
import de.hdm.wim.ComplexTokenEvent
import de.hdm.wim.Event

//declare any global variables here
declare Event
	@role(event)
end
declare ComplexTokenEvent
	@role(event)
end

declare window LastEvents
	// Aktuelle wird mitgezaehlt
	Event() over window:length(2)
end

declare window LastComplexTokenEvent
	ComplexTokenEvent() over window:length(1)
end

rule "Recognize project based relation"
	no-loop
	when
		$expectRelation : Event(
			token == "concerning"
			|| token == "regarding"
		) from window LastEvents
		$relation : Event(
			this after $expectRelation
		)
		$complexTokenEvent : ComplexTokenEvent() from window LastComplexTokenEvent
	then
		modify($complexTokenEvent) {
			setRelatedToProject($relation.getToken())
		}
end
