//created on: 09.01.2017
package de.hdm.wim

//list any import classes here.
import de.hdm.wim.ComplexToken
import de.hdm.wim.Event

//declare any global variables here
declare Event
	@role(event)
end

declare window LastEvents
	// Aktuelle wird mitgezaehlt
    Event() over window:length(2)
end

/*
 * Time based
rule "Recognize project based restriction"
    when
       	$awaitRestriction : Event(
       		token == "concerning"
        	|| token == "leading to"
       	)
       	$restriction : Event(
       		this after[0s, 2s] $awaitRestriction,
       		this != $awaitRestriction
       	)
    then
    	System.out.println("Restriction: " + $restriction.getToken());
end*/

rule "Recognize project based restriction"
    when
       	$expectRestriction : Event(
       		token == "concerning"
        	|| token == "leading to"
       	) from window LastEvents
       	$restriction : Event(
       		this after $expectRestriction
       	)
       	$complexToken : ComplexToken()
    then
    	$complexToken.setRestrictedToProject($restriction.getToken());
    	System.out.println("Restriction: " + $restriction.getToken());
end